name: Gource Action
on:
  push:
    branches:
      - yuuka-v2

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: 'Create Branch and Push Video'
        run: |
          git checkout -b gource-visualisation
          git add ./gource/gource.mp4
          git commit -m "Add Gource visualization video"
          git push origin gource-visualisation